spring.application.name=Tyson-housing

spring.datasource.url=jdbc:postgresql://localhost:5432/tyson
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mvn spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://localhost:5432/tyson --spring.datasource.username=postgres --spring.datasource.password=postgres"